steps:
  build-release:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: "${CI_REPO_OWNER##mu-}/${CI_REPO_NAME%%-service}"
      tags: "${CI_COMMIT_TAG##v}"
      platforms: linux/amd64
    secrets: [ docker_username, docker_password ]
when:
  event: tag
  tag: v*
